import p1 from '../../assets/images/product/p1.jpg'
import p2 from '../../assets/images/product/p2.jpg'
import p3 from '../../assets/images/product/p3.jpg'
import p4 from '../../assets/images/product/p4.jpg'
import p5 from '../../assets/images/product/p5.jpg'
import p6 from '../../assets/images/product/p6.jpg'
import p7 from '../../assets/images/product/p7.avif'
import p8 from '../../assets/images/product/p8.avif'
import p9 from '../../assets/images/product/p9.avif'
import p10 from '../../assets/images/product/p10.avif'
import p11 from '../../assets/images/product/p11.avif'
import p12 from '../../assets/images/product/p12.avif'
import p13 from '../../assets/images/product/p13.avif'

import type { ProductExtended } from '../../types'

export const PRODUCTS_DATA: ProductExtended[] = [
  // ==========================================
  // WOMEN - SKINCARE COLLECTION
  // ==========================================
  {
    id: 1,
    name: 'Botanical Radiance Glow Serum',
    price: 34.00,
    discountPrice: 28.00,
    rating: 4.9,
    reviewsCount: 148,
    category: 'Serums',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p1,
    hoverImg: p4,
    badge: 'Best Seller',
    description: 'High-potency botanical serum infused with active plant peptides for instant luminosity and deep cellular renewal.',
    inStock: true,
  },
  {
    id: 2,
    name: 'Bio-Active Barrier Repair Cream',
    price: 32.00,
    discountPrice: 26.00,
    rating: 4.8,
    reviewsCount: 112,
    category: 'Moisturizers',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p2,
    hoverImg: p7,
    badge: 'Popular',
    description: 'Rich ceramide-complex moisturizer that fortifies the moisture barrier and locks in deep hydration for 48 hours.',
    inStock: true,
  },
  {
    id: 3,
    name: 'Gentle Clarifying Foaming Wash',
    price: 24.00,
    discountPrice: 19.00,
    rating: 4.7,
    reviewsCount: 95,
    category: 'Cleansers',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p3,
    hoverImg: p8,
    badge: 'Essential',
    description: 'pH-balanced purifying cleanser with green tea and chamomile to dissolve impurities without stripping essential moisture.',
    inStock: true,
  },
  {
    id: 4,
    name: 'Hyaluronic Dew Plumping Elixir',
    price: 36.00,
    discountPrice: 30.00,
    rating: 4.9,
    reviewsCount: 180,
    category: 'Serums',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p4,
    hoverImg: p1,
    badge: 'Trending',
    description: 'Multi-molecular hyaluronic acid elixir that penetrates multiple skin layers for bouncy, dewy, intensely plumped skin.',
    inStock: true,
  },
  {
    id: 5,
    name: 'Niacinamide Pore Tightening Serum',
    price: 30.00,
    discountPrice: 25.00,
    rating: 4.8,
    reviewsCount: 134,
    category: 'Serums',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p5,
    hoverImg: p9,
    description: '10% Niacinamide + Zinc PCA formula designed to visibly minimize enlarged pores, regulate sebum, and even skin tone.',
    inStock: true,
  },
  {
    id: 6,
    name: 'Retinol Cellular Renewal Treatment',
    price: 42.00,
    discountPrice: 35.00,
    rating: 4.9,
    reviewsCount: 210,
    category: 'Treatments',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p6,
    hoverImg: p10,
    badge: 'Clinical Grade',
    description: 'Encapsulated gentle retinol system that accelerates cell turnover, smooths fine lines, and promotes firm skin texture.',
    inStock: true,
  },
  {
    id: 7,
    name: 'Centella Soothing Calming Gel',
    price: 28.00,
    discountPrice: 22.00,
    rating: 4.8,
    reviewsCount: 89,
    category: 'Moisturizers',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p7,
    hoverImg: p2,
    description: 'Ultra-lightweight soothing gel formulated with 80% Centella Asiatica extract to instantly calm redness and irritation.',
    inStock: true,
  },
  {
    id: 8,
    name: 'Bakuchiol Natural Firming Elixir',
    price: 38.00,
    discountPrice: 31.00,
    rating: 4.9,
    reviewsCount: 125,
    category: 'Serums',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p8,
    hoverImg: p5,
    badge: 'New',
    description: 'Plant-derived alternative to retinol that delivers age-defying firmness and elasticity without photosensitivity.',
    inStock: true,
  },
  {
    id: 9,
    name: 'Salicylic Purifying Exfoliant Tonic',
    price: 26.00,
    discountPrice: 21.00,
    rating: 4.7,
    reviewsCount: 103,
    category: 'Treatments',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p9,
    hoverImg: p3,
    description: '2% BHA liquid exfoliant that unclogs congested pores, clears blemishes, and refines uneven skin surface texture.',
    inStock: true,
  },
  {
    id: 10,
    name: 'Ceramide Deep Moisture Hydro-Gel',
    price: 33.00,
    discountPrice: 27.00,
    rating: 4.8,
    reviewsCount: 76,
    category: 'Moisturizers',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p10,
    hoverImg: p6,
    description: 'Refreshing water-burst gel packed with 5 essential ceramides for long-lasting, weightless hydration on combo skin.',
    inStock: true,
  },
  {
    id: 11,
    name: 'Peptide Collagen Boost Fluid',
    price: 40.00,
    discountPrice: 34.00,
    rating: 4.9,
    reviewsCount: 162,
    category: 'Serums',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p11,
    hoverImg: p1,
    badge: 'Top Rated',
    description: 'Concentrated matrixyl peptide serum engineered to restore skin resilience, firmness, and natural collagen density.',
    inStock: true,
  },
  {
    id: 12,
    name: 'Vitamin E Overnight Recovery Mask',
    price: 29.00,
    discountPrice: 24.00,
    rating: 4.8,
    reviewsCount: 98,
    category: 'Masks',
    department: 'women',
    productType: 'skincare',
    brand: 'Morkins',
    img: p12,
    hoverImg: p2,
    description: 'Nourishing sleeping mask infused with antioxidant Tocopherol and squalane to heal, revive, and brighten tired skin overnight.',
    inStock: true,
  },

  // ==========================================
  // WOMEN - HAIRCARE COLLECTION
  // ==========================================
  {
    id: 13,
    name: 'Botanical Scalp & Hair Density Serum',
    price: 35.00,
    discountPrice: 29.00,
    rating: 4.9,
    reviewsCount: 140,
    category: 'Serums',
    department: 'women',
    productType: 'haircare',
    brand: 'Morkins',
    img: p13,
    hoverImg: p11,
    badge: 'Hair Care',
    description: 'Multi-peptide scalp density treatment stimulating follicle vitality for thicker, fuller, and stronger hair strands.',
    inStock: true,
  },
  {
    id: 14,
    name: 'Silk Peptide Repair Hair Mask',
    price: 32.00,
    discountPrice: 26.00,
    rating: 4.8,
    reviewsCount: 88,
    category: 'Masks',
    department: 'women',
    productType: 'haircare',
    brand: 'Morkins',
    img: p1,
    hoverImg: p8,
    badge: 'Trending',
    description: 'Intense reconstructive mask infused with hydrolysed silk protein and argan oil to reverse chemical and heat damage.',
    inStock: true,
  },
  {
    id: 15,
    name: 'Gentle Rosemary Scalp Clarifier',
    price: 26.00,
    discountPrice: 21.00,
    rating: 4.7,
    reviewsCount: 65,
    category: 'Cleansers',
    department: 'women',
    productType: 'haircare',
    brand: 'Morkins',
    img: p3,
    hoverImg: p9,
    description: 'Sulfate-free scalp shampoo with rosemary oil and tea tree to detoxify buildup and soothe itchy scalp.',
    inStock: true,
  },
  {
    id: 16,
    name: 'Argan Moisture Infusion Hair Cream',
    price: 28.00,
    discountPrice: 23.00,
    rating: 4.8,
    reviewsCount: 52,
    category: 'Moisturizers',
    department: 'women',
    productType: 'haircare',
    brand: 'Morkins',
    img: p2,
    hoverImg: p10,
    description: 'Leave-in hydrating conditioner smoothing frizz, defining curls, and adding a brilliant mirror-like gloss.',
    inStock: true,
  },

  // ==========================================
  // MEN - SKINCARE COLLECTION
  // ==========================================
  {
    id: 17,
    name: 'Men Active Charcoal Detox Cleanser',
    price: 24.00,
    discountPrice: 19.00,
    rating: 4.8,
    reviewsCount: 84,
    category: 'Cleansers',
    department: 'men',
    productType: 'skincare',
    brand: 'Morkins',
    img: p3,
    hoverImg: p5,
    badge: 'Popular',
    description: 'Activated bamboo charcoal foaming wash formulated to draw out toxins, unclog tough pores, and stop post-workout breakouts.',
    inStock: true,
  },
  {
    id: 18,
    name: 'Men Ultra-Matte Oil-Control Gel',
    price: 30.00,
    discountPrice: 24.00,
    rating: 4.7,
    reviewsCount: 96,
    category: 'Moisturizers',
    department: 'men',
    productType: 'skincare',
    brand: 'Morkins',
    img: p7,
    hoverImg: p2,
    badge: 'Essential',
    description: 'Non-greasy hydrating lotion providing an instant matte finish with sebum-regulating zinc and witch hazel.',
    inStock: true,
  },
  {
    id: 19,
    name: 'Men Post-Shave Calming Recovery Fluid',
    price: 28.00,
    discountPrice: 22.00,
    rating: 4.9,
    reviewsCount: 110,
    category: 'Treatments',
    department: 'men',
    productType: 'skincare',
    brand: 'Morkins',
    img: p6,
    hoverImg: p4,
    badge: 'Best Seller',
    description: 'Alcohol-free soothing serum enriched with aloe and centella to prevent razor burns, bumps, and ingrown hairs.',
    inStock: true,
  },
  {
    id: 20,
    name: 'Men Hyaluronic Energy Surge Serum',
    price: 34.00,
    discountPrice: 28.00,
    rating: 4.8,
    reviewsCount: 73,
    category: 'Serums',
    department: 'men',
    productType: 'skincare',
    brand: 'Morkins',
    img: p4,
    hoverImg: p1,
    description: 'Caffeine and hyaluronic acid energizing concentrate that revitalizes tired, dull male skin and reduces eye puffiness.',
    inStock: true,
  },

  // ==========================================
  // MEN - HAIRCARE COLLECTION
  // ==========================================
  {
    id: 21,
    name: 'Men Anti-Dandruff Tea Tree Scalp Wash',
    price: 25.00,
    discountPrice: 20.00,
    rating: 4.8,
    reviewsCount: 122,
    category: 'Cleansers',
    department: 'men',
    productType: 'haircare',
    brand: 'Morkins',
    img: p9,
    hoverImg: p3,
    badge: 'Top Rated',
    description: 'Therapeutic shampoo powered by tea tree and zinc pyrithione to eliminate stubborn flakes and calm scalp irritation.',
    inStock: true,
  },
  {
    id: 22,
    name: 'Men Biotin Follicle Fortifier Serum',
    price: 36.00,
    discountPrice: 29.00,
    rating: 4.9,
    reviewsCount: 145,
    category: 'Serums',
    department: 'men',
    productType: 'haircare',
    brand: 'Morkins',
    img: p13,
    hoverImg: p12,
    badge: 'Best Seller',
    description: 'Advanced follicle stimulation serum with 5% Redensyl and Biotin to combat thinning and promote robust new growth.',
    inStock: true,
  },
  {
    id: 23,
    name: 'Men Matte Texture Styling Clay Mask',
    price: 27.00,
    discountPrice: 22.00,
    rating: 4.7,
    reviewsCount: 68,
    category: 'Masks',
    department: 'men',
    productType: 'haircare',
    brand: 'Morkins',
    img: p10,
    hoverImg: p7,
    description: 'Natural bentonite clay cream offering strong hold, zero shine, and nourishing conditioning benefits for shorter hair.',
    inStock: true,
  },
];

// Helper functions for API calls
export async function getProducts(): Promise<ProductExtended[]> {
  return new Promise((resolve) => {
    setTimeout(() => resolve([...PRODUCTS_DATA]), 50);
  });
}

export async function getProductById(id: number): Promise<ProductExtended | undefined> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(PRODUCTS_DATA.find(p => p.id === id)), 50);
  });
}

export async function getBestSellers(): Promise<ProductExtended[]> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(PRODUCTS_DATA.filter(p => p.badge === 'Best Seller' || p.rating >= 4.9)), 50);
  });
}

export async function getNewArrivals(): Promise<ProductExtended[]> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(PRODUCTS_DATA.filter(p => p.badge === 'New' || p.badge === 'Trending' || p.id >= 10)), 50);
  });
}
